import { PDFDocument, StandardFonts } from 'pdf-lib'
import { writeFile } from 'node:fs/promises'

const doc = await PDFDocument.create()
const page = doc.addPage()
const font = await doc.embedFont(StandardFonts.Helvetica)
const text = 'Hello MindMap. This is a real PDF generated by pdf-lib for the upload pipeline test.'
page.drawText(text, { x: 50, y: 700, size: 14, font })

const bytes = await doc.save()
await writeFile('/tmp/real.pdf', bytes)
console.log('Wrote /tmp/real.pdf,', bytes.byteLength, 'bytes')
